# Generated by Django 3.0.3 on 2020-05-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PestApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaCaptchastore',
        ),
    ]
